// Package expertai_esg provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package expertai_esg

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Request
type AnalysisRequest struct {
	// Document
	Document *Document `json:"document,omitempty"`
}

// Category
type Category struct {
	// Score expressed as a percentage of the sum of the scores of all the candidate categories, winners and not (see the **score** property)
	Frequency *float32 `json:"frequency,omitempty"`

	// Hierarchical path
	Hierarchy *[]string `json:"hierarchy,omitempty"`

	// Category ID
	Id *string `json:"id,omitempty"`

	// Category label
	Label *string `json:"label,omitempty"`

	// Name of the software package containing the reference taxonomy
	Namespace *string `json:"namespace,omitempty"`

	// Positions of the portions of text that contributed to the selection of the category
	Positions *[]DocumentPosition `json:"positions,omitempty"`

	// Score assigned to the category to represent its relevance
	Score *int32 `json:"score,omitempty"`

	// True if the category is deemed particularly relevant
	Winner *bool `json:"winner,omitempty"`
}

// Document
type Document struct {
	// The document's text
	Text *string `json:"text,omitempty"`
}

// Position
type DocumentPosition struct {
	// Zero-based position of the character after the last
	End *int64 `json:"end,omitempty"`

	// Zero-based position of the first character
	Start *int64 `json:"start,omitempty"`
}

// Information detection data
type ESGSentimentDetectDocument struct {
	// ESG categories with sentiment connotation, for example: 'Environment/Positive/Waste and Emissions Management' or 'Governance/Negative/Legal Compliance'"
	Categories *[]Category `json:"categories,omitempty"`

	// Extractions of entities with ESG data and overall ESG sentiment scores. For example: 'entity=Acme Ltd., pollution_reduced=25%' or 'environment_performance_score=365'.
	Extractions *[]Extraction `json:"extractions,omitempty"`

	// Text language
	Language *string `json:"language,omitempty"`

	// Service version
	Version *string `json:"version,omitempty"`
}

// ESG Sentiment detection resource response
type ESGSentimentDetectResponse struct {
	// Information detection data
	Data *ESGSentimentDetectDocument `json:"data,omitempty"`

	// Service errors
	Errors *[]ServiceError `json:"errors,omitempty"`

	// Operation completed successfully (true/false)
	Success *bool `json:"success,omitempty"`
}

// Extraction record
type Extraction struct {
	// Extraction record fields
	Fields *[]struct {
		// Field name
		Name *string `json:"name,omitempty"`

		// Positions of parts of the text corresponding to the field value
		Positions *[]DocumentPosition `json:"positions,omitempty"`

		// Field value
		Value *string `json:"value,omitempty"`
	} `json:"fields,omitempty"`

	// Software package name
	Namespace *string `json:"namespace,omitempty"`

	// Extraction record template
	Template *string `json:"template,omitempty"`
}

// Error information
type ServiceError struct {
	// Error code
	Code *string `json:"code,omitempty"`

	// Error message
	Message *string `json:"message,omitempty"`
}

// PostDetectEsgSentimentLanguageJSONBody defines parameters for PostDetectEsgSentimentLanguage.
type PostDetectEsgSentimentLanguageJSONBody = AnalysisRequest

// PostDetectEsgSentimentLanguageJSONRequestBody defines body for PostDetectEsgSentimentLanguage for application/json ContentType.
type PostDetectEsgSentimentLanguageJSONRequestBody = PostDetectEsgSentimentLanguageJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostDetectEsgSentimentLanguage request with any body
	PostDetectEsgSentimentLanguageWithBody(ctx context.Context, language string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostDetectEsgSentimentLanguage(ctx context.Context, language string, body PostDetectEsgSentimentLanguageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostDetectEsgSentimentLanguageWithBody(ctx context.Context, language string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDetectEsgSentimentLanguageRequestWithBody(c.Server, language, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostDetectEsgSentimentLanguage(ctx context.Context, language string, body PostDetectEsgSentimentLanguageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDetectEsgSentimentLanguageRequest(c.Server, language, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostDetectEsgSentimentLanguageRequest calls the generic PostDetectEsgSentimentLanguage builder with application/json body
func NewPostDetectEsgSentimentLanguageRequest(server string, language string, body PostDetectEsgSentimentLanguageJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostDetectEsgSentimentLanguageRequestWithBody(server, language, "application/json", bodyReader)
}

// NewPostDetectEsgSentimentLanguageRequestWithBody generates requests for PostDetectEsgSentimentLanguage with any type of body
func NewPostDetectEsgSentimentLanguageRequestWithBody(server string, language string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "language", runtime.ParamLocationPath, language)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/detect/esg-sentiment/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostDetectEsgSentimentLanguage request with any body
	PostDetectEsgSentimentLanguageWithBodyWithResponse(ctx context.Context, language string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostDetectEsgSentimentLanguageResponse, error)

	PostDetectEsgSentimentLanguageWithResponse(ctx context.Context, language string, body PostDetectEsgSentimentLanguageJSONRequestBody, reqEditors ...RequestEditorFn) (*PostDetectEsgSentimentLanguageResponse, error)
}

type PostDetectEsgSentimentLanguageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ESGSentimentDetectResponse
}

// Status returns HTTPResponse.Status
func (r PostDetectEsgSentimentLanguageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostDetectEsgSentimentLanguageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostDetectEsgSentimentLanguageWithBodyWithResponse request with arbitrary body returning *PostDetectEsgSentimentLanguageResponse
func (c *ClientWithResponses) PostDetectEsgSentimentLanguageWithBodyWithResponse(ctx context.Context, language string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostDetectEsgSentimentLanguageResponse, error) {
	rsp, err := c.PostDetectEsgSentimentLanguageWithBody(ctx, language, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDetectEsgSentimentLanguageResponse(rsp)
}

func (c *ClientWithResponses) PostDetectEsgSentimentLanguageWithResponse(ctx context.Context, language string, body PostDetectEsgSentimentLanguageJSONRequestBody, reqEditors ...RequestEditorFn) (*PostDetectEsgSentimentLanguageResponse, error) {
	rsp, err := c.PostDetectEsgSentimentLanguage(ctx, language, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDetectEsgSentimentLanguageResponse(rsp)
}

// ParsePostDetectEsgSentimentLanguageResponse parses an HTTP response from a PostDetectEsgSentimentLanguageWithResponse call
func ParsePostDetectEsgSentimentLanguageResponse(rsp *http.Response) (*PostDetectEsgSentimentLanguageResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostDetectEsgSentimentLanguageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ESGSentimentDetectResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
